solr:
  image: 'makuk66/docker-solr:4.10.4'
  user: root
  expose:
    - '8983'
  volumes:
    - ~/data/solr:/opt/solr/example/solr
redis:
  image: library/redis
  ports:
    - '6379'
  volumes_from:
    - data

memcached:
  image: tutum/memcached
  ports:
    - '11211'
  environment:
    - MEMCACHED_PASS=""

mysql:
  image: 'mysql:5.5'
  expose:
    - '3306'
  environment:
    - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'
  volumes_from:
    - data
  
teamcity:
  build: ./server
  user: root
  ports:
    - '8111:8111'
  volumes_from:
    - data
    - sshdata
  links:
    - mysql:mysql

agent:
  build: ./agent
  environment:
    - 'TEAMCITY_SERVER=http://teamcity:8111'
    - 'DEFAULT_RUBIES=2.2.1 1.9.3'
    - 'DEAULT_GEMSETS=app1 app2'
  ports:
    - '9090' 
  links:
    - mysql
    - memcached
    - redis
    - solr
  volumes_from:
    - sshdata

sshdata:
  image: busybox
  command: /bin/true
  volumes:
    - ~/.ssh:/root/.ssh

data:
  image: busybox
  command: /bin/true
  volumes:
    - /var/lib/mysql
    - ~/data/solr:/opt/solr/example/solr
    - ~/data/redis:/data
    - ~/data/teamcity:/data/teamcity
