mysql:
  image: 'mysql:5.5'
  expose:
    - '3306'
  environment:
    - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'
  volumes_from:
    - data
  
teamcity:
  build: ./server
  user: root
  ports:
    - '8111:8111'
  volumes_from:
    - data
    - sshdata
  links:
    - mysql:mysql

agent:
  build: ./agent
  environment:
    - 'TEAMCITY_SERVER=http://192.168.40.123:8111'
    - 'DEFAULT_DATABASE=modyo_develop'
  ports:
    - '9090' 
  volumes_from:
    - sshdata

sshdata:
  image: busybox
  command: /bin/true
  volumes:
    - ~/.ssh:/root/.ssh

data:
  image: busybox
  command: /bin/true
  volumes:
    - /var/lib/mysql
    - ~/data/solr:/opt/solr/example/solr
    - ~/data/redis:/data
    - ~/data/teamcity:/data/teamcity
