solr:
  image: 'makuk66/docker-solr:4.10.4'
  user: root
  ports:
    - '8080:8983'
  volumes:
    - ~/data/solr:/opt/solr/example/solr
redis:
  image: dockerfile/redis
  ports:
    - '6379'

memcached:
  image: tutum/memcached
  ports:
    - '11211'
  environment:
    - MEMCACHED_PASS=""

mysql:
  image: 'mysql:5.5'
  expose:
    - 3306
  environment:
    - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'
  volumes_from:
    - data
  
teamcityserver:
  image: 'server_teamcity'
  ports:
    - '8111'
  volumes_from:
    - data

teamcityagent:
  image: 'agent_teamcity'
  environment:
    - 'TEAMCITY_SERVER=http://192.168.50.103:8111'
  ports:
    - '9090' 
  links:
    - mysql
    - memcached
    - redis
    - solr

data:
  image: busybox
  command: /bin/true
  volumes:
    - /var/lib/mysql
    - ~/data/solr:/opt/solr/example/solr
